name: chocolatine

on: [push, pull_request]

env:
  EXECUTABLES: "107transfer"
  MIRROR_URL: git@github.com:Akashi05/cho.git

jobs:
    check_coding_style:
      runs-on: ubuntu-latest
      container:
        image: ghcr.io/epitech/coding-style-checker:latest
      steps:
        - name:
          uses: actions/checkout@v4

        - name: coding_style checking
          run: |
            check.sh $(pwd) $(pwd)
            if [ -f $coding-style-reports.log ]; then
                ls
                cat coding-style-reports.log
            else
                ls
            fi

    check_program_compilation:
      needs: check_coding_style
      runs-on: ubuntu-latest
      container:
        image: epitechcontent/epitest-docker:latest
      steps:
        - name:
          uses: actions/checkout@v4

        - name: make step and binary verif
          run: |
            make
            if [ ! -f $EXECUTABLES ]; then
                exit 1
            fi

        - name: make clean step
          run: make clean

    run_tests:
      needs: check_program_compilation
      runs-on: ubuntu-latest
      container:
        image: epitechcontent/epitest-docker:latest
      steps:
        - name:
          uses: actions/checkout@v4
        - name:
          run: make tests_run

    push_to_mirror:
      needs: run_tests
      runs-on: ubuntu-latest
      steps:
        - name:
          uses: actions/checkout@v4

        - name: mirroring
          uses: pixta-dev/repository-mirroring-action@v1
          with:
            target_repo_url:
              ${{ env.MIRROR_URL }}
            ssh_private_key:
              ${{ secrets.GIT_SSH_PRIVATE_KEY}}
  